apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - services.yaml

images:
  - name: ai-assistant
    newName: ai-assistant
    newTag: latest
